//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MehmetEgitKurumsal.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralSetting
    {
        public int ID { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string LogoUrl { get; set; }
        public string FacebookUrl { get; set; }
        public string TwitterUrl { get; set; }
        public string InstagramUrl { get; set; }
        public string Address { get; set; }
        public string GoogleMapsCode { get; set; }
        public Nullable<int> UserCount { get; set; }
        public Nullable<int> EducationVideoCount { get; set; }
        public Nullable<int> WatchHour { get; set; }
        public string FooterNote { get; set; }
        public string YoutubeUrl { get; set; }
    }
}
