//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MehmetEgitKurumsal.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public Nullable<int> SubID { get; set; }
        public Nullable<int> SortNumber { get; set; }
        public Nullable<bool> ActOrPass { get; set; }
        public string Description { get; set; }
    }
}
