//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MehmetEgitKurumsal.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Packet()
        {
            this.Purchases = new HashSet<Purchase>();
            this.Videos = new HashSet<Video>();
        }
    
        public int ID { get; set; }
        public string PackageName { get; set; }
        public string PacketDesc { get; set; }
        public string PacketImgUrl { get; set; }
        public string SeoUrlLink { get; set; }
        public Nullable<double> PacketPrice { get; set; }
        public Nullable<bool> ActOrPass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video> Videos { get; set; }
    }
}
